version: '3.1'
services:
  db:
    container_name: discord-gateway-db
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5432:5432
  back:
    container_name: discord-gateway
    image: dota2classic/matchmaking:discord-gateway
    env_file:
      - ./.env
    volumes:
      - ./storage:/usr/src/app/dist/upload
    ports:
      - 0.0.0.0:5001:5001