version: '3.1'
services:
  discord-db:
    container_name: d2c-db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5432:5432
  discord:
    depends_on:
      - discord-db
      - redis
    container_name: discord-gateway
    image: dota2classic/matchmaking:discord-gateway
    env_file:
      - ./.env
  core:
    depends_on:
      - redis
    container_name: matchmaking-core
    image: dota2classic/matchmaking:core
    env_file:
      - ./.env
  user:
    depends_on:
      - redis
    container_name: d2c-user
    image: dota2classic/matchmaking:user-service
    env_file:
      - ./.env
    ports:
      - 0.0.0.0:5000:5000
  redis:
    container_name: matchmaking-redis
    image: bitnami/redis:alpine

    command: redis-server

    ports:
      - 0.0.0.0:6379:6379

    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
