version: '3.1'
services:
  discord-db:
    container_name: discord-gateway-db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5432:5432
  match-db:
    container_name: dota2db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./match-storage:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5400:5432
  discord:
    depends_on:
      - discord-db
      - redis
    container_name: discord-gateway
    image: dota2classic/matchmaking:discord-gateway
    env_file:
      - ./.env
    environment:
      - CORE_GATEWAY_HOST=core
      - DISCORD_GATEWAY_HOST=discord
      - REDIS_URL=redis://redis:6379
  core:
    depends_on:
      - redis
    container_name: matchmaking-core
    image: dota2classic/matchmaking:core
    environment:
      - CORE_GATEWAY_HOST=core
      - DISCORD_GATEWAY_HOST=discord
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./.env
    ports:
      - 0.0.0.0:5000:5000
  redis:
    container_name: matchmaking-redis
    image: 'redis:alpine'

    command: redis-server

    ports:
      - 0.0.0.0:6379:6379

    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
